CREATE USER IF NOT EXISTS jwduser IDENTIFIED BY 'pass';

DROP DATABASE IF EXISTS OnlineShopJPAReact;
CREATE DATABASE OnlineShopJPAReact DEFAULT CHARACTER SET utf8;

USE OnlineShopJPAReact;

GRANT ALL ON OnlineShopJPAReact.* TO 'jwduser'@'%';

FLUSH PRIVILEGES;